### PR TITLE
Introduce pre-release version of electron-localshortcut

### PR DESCRIPTION
**Pull request by parro-it**
With this PR I introduced dependency on a pre-release version of electron-localshortcut that implement DOM event based shortcuts management.

This version should solve all the problem we had with windows lifecycle management.

The new version is still lacking some implementation, but the part used by `electron-debug` (and `Caprine` btw) is done.

It could be useful to have someone other test this PR (I tested on Ubuntu 17) and seems to work just fine.

### CODE REVIEW

**Comment by parro-it** [comment]
Hi Sindre, I saw you merged this. 
Did you or some other test this on Windows and macOS? As I said, I tested it only on Ubuntu...

**Comment by sindresorhus** [comment]
I tested it on macOS and worked fine.

**Comment by parro-it** [comment]
😎😗

**Comment by parro-it** [comment]
Typed a kiss for mistake on my phone 😂

**Pull request merged**
